# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    config.vm.provider "virtualbox" do |vbox|
        vbox.name = "nuc-server"
    end


    config.vm.define :nucServer do |nucServer|
        # Every Vagrant virtual environment requires a box to build off of.
        nucServer.vm.box = "ubuntu/trusty64"

$script = <<SCRIPT
cd /vagrant
echo "Installing cabextract..."
sudo apt-get -qq install cabextract
./provision.sh
SCRIPT

        nucServer.vm.provision "shell", inline: $script, privileged: false
    end
end
