# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder ".", "/home/vagrant/workstation-provision/", owner: "vagrant", group: "vagrant"

$script = <<SCRIPT
cd ~/workstation-provision
echo "Installing ubuntu-desktop for package compatibility..."
sudo apt-get install -qq ubuntu-desktop
./provision.sh
SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false

end
