# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :ubuntu14_04 do |ubuntu14_04|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    ubuntu14_04.provider "virtualbox" do |vbox|
      vbox.name = "Ubuntu LTS Provisioning Assistant"
    end

    # Every Vagrant virtual environment requires a box to build off of.
    ubuntu14_04.vm.box = "ubuntu/trusty64"

$script = <<SCRIPT
cd ~/workstation-provision
echo "Installing cabextract..."
sudo apt-get -qq install cabextract
./provision.sh
SCRIPT

    ubuntu14_04.vm.provision "shell", inline: $script, privileged: false
  end

end
